### ISSUE TITLE
Feature mousin/mouseout not fired during pan momentum and zoom

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geojs#260]

**Comment by aashish24** [comment]
@manthey I think this is resolved?

**Comment by manthey** [comment]
If a point passes under the mouse because of momentum, the events are not fired.  This is still an issue.
